/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
long fir_int[36]  = 
  {      4294967294L,      1L,      4L,      3L, 
        4294967294L,      4294967292L,      2L,      7L, 
        0L,      4294967287L,      4294967292L,      12L, 
        11L,      4294967282L,      4294967270L,      15L, 
        89L,      127L,      89L,      15L, 
        4294967270L,      4294967282L,      11L,      12L, 
        4294967292L,      4294967287L,      0L,      7L, 
        2L,      4294967292L,      4294967294L,      3L, 
        4L,      1L,      4294967294L,      0L};
long in_data[701]  = 
  {      0L,      0L,      0L,      0L, 
        127L,      121L,      114L,      121L, 
        13L,      13L,      0L,      3L, 
        5L,      2L,      3L,      127L, 
        127L,      2L,      126L,      0L, 
        1L,      126L,      1L,      1L, 
        127L,      0L,      127L,      0L, 
        2L,      1L,      1L,      3L, 
        1L,      127L,      1L,      0L, 
        1L,      1L,      125L,      123L, 
        115L,      106L,      119L,      16L, 
        14L,      1L,      5L,      5L, 
        5L,      5L,      125L,      0L, 
        2L,      125L,      0L,      0L, 
        126L,      1L,      126L,      127L, 
        3L,      124L,      126L,      6L, 
        0L,      126L,      3L,      2L, 
        127L,      126L,      127L,      2L, 
        1L,      127L,      1L,      1L, 
        0L,      3L,      0L,      127L, 
        2L,      0L,      127L,      3L, 
        1L,      0L,      0L,      125L, 
        0L,      3L,      0L,      126L, 
        127L,      2L,      1L,      126L, 
        0L,      3L,      127L,      125L, 
        1L,      1L,      1L,      127L, 
        0L,      5L,      0L,      127L, 
        2L,      126L,      127L,      2L, 
        1L,      0L,      126L,      0L, 
        5L,      0L,      127L,      0L, 
        126L,      1L,      0L,      125L, 
        1L,      3L,      127L,      0L, 
        0L,      126L,      2L,      3L, 
        126L,      125L,      114L,      104L, 
        113L,      5L,      12L,      7L, 
        2L,      6L,      13L,      5L, 
        125L,      3L,      2L,      127L, 
        0L,      121L,      122L,      3L, 
        126L,      125L,      0L,      125L, 
        2L,      1L,      125L,      8L, 
        3L,      124L,      6L,      0L, 
        122L,      6L,      2L,      124L, 
        3L,      126L,      121L,      6L, 
        5L,      116L,      127L,      13L, 
        122L,      120L,      6L,      5L, 
        1L,      0L,      125L,      1L, 
        4L,      124L,      127L,      3L, 
        127L,      5L,      3L,      122L, 
        6L,      10L,      118L,      124L, 
        10L,      124L,      127L,      6L, 
        121L,      3L,      12L,      117L, 
        120L,      10L,      0L,      121L, 
        3L,      126L,      124L,      6L, 
        0L,      121L,      2L,      126L, 
        127L,      6L,      118L,      127L, 
        13L,      121L,      127L,      6L, 
        121L,      6L,      3L,      113L, 
        6L,      10L,      115L,      127L, 
        10L,      0L,      127L,      122L, 
        124L,      10L,      0L,      117L, 
        127L,      12L,      10L,      124L, 
        121L,      9L,      13L,      125L, 
        122L,      5L,      11L,      10L, 
        121L,      124L,      22L,      3L, 
        114L,      13L,      7L,      121L, 
        12L,      7L,      122L,      11L, 
        7L,      122L,      10L,      7L, 
        121L,      10L,      5L,      117L, 
        6L,      5L,      121L,      5L, 
        6L,      1L,      6L,      0L, 
        122L,      2L,      7L,      3L, 
        125L,      1L,      10L,      7L, 
        2L,      127L,      127L,      9L, 
        7L,      121L,      121L,      6L, 
        8L,      125L,      122L,      6L, 
        12L,      6L,      125L,      127L, 
        13L,      7L,      121L,      1L, 
        6L,      127L,      127L,      2L, 
        3L,      1L,      126L,      1L, 
        1L,      125L,      1L,      0L, 
        125L,      6L,      3L,      125L, 
        5L,      7L,      127L,      124L, 
        1L,      6L,      6L,      124L, 
        122L,      7L,      10L,      0L, 
        120L,      1L,      8L,      0L, 
        121L,      122L,      4L,      10L, 
        0L,      120L,      1L,      6L, 
        122L,      117L,      122L,      0L, 
        0L,      121L,      118L,      127L, 
        7L,      0L,      122L,      125L, 
        2L,      4L,      124L,      122L, 
        2L,      5L,      124L,      122L, 
        125L,      127L,      0L,      120L, 
        117L,      127L,      0L,      121L, 
        120L,      121L,      1L,      3L, 
        121L,      121L,      0L,      0L, 
        127L,      127L,      121L,      127L, 
        2L,      122L,      124L,      125L, 
        124L,      127L,      125L,      121L, 
        125L,      0L,      121L,      122L, 
        124L,      125L,      0L,      125L, 
        125L,      0L,      0L,      0L, 
        0L,      125L,      125L,      0L, 
        125L,      126L,      0L,      126L, 
        3L,      3L,      125L,      1L, 
        5L,      0L,      126L,      125L, 
        127L,      3L,      125L,      121L, 
        1L,      2L,      125L,      127L, 
        1L,      0L,      0L,      127L, 
        127L,      126L,      127L,      0L, 
        127L,      0L,      124L,      125L, 
        0L,      121L,      120L,      124L, 
        124L,      123L,      123L,      125L, 
        127L,      0L,      0L,      127L, 
        0L,      1L,      2L,      0L, 
        127L,      0L,      0L,      0L, 
        127L,      126L,      0L,      0L, 
        127L,      0L,      2L,      1L, 
        2L,      6L,      5L,      3L, 
        6L,      8L,      5L,      2L, 
        1L,      1L,      3L,      0L, 
        125L,      127L,      0L,      127L, 
        126L,      0L,      2L,      3L, 
        2L,      1L,      2L,      3L, 
        1L,      124L,      125L,      0L, 
        0L,      126L,      124L,      127L, 
        1L,      0L,      126L,      124L, 
        127L,      1L,      0L,      126L, 
        127L,      2L,      3L,      1L, 
        0L,      4L,      6L,      5L, 
        6L,      7L,      10L,      10L, 
        4L,      2L,      5L,      8L, 
        9L,      8L,      7L,      12L, 
        20L,      20L,      16L,      14L, 
        20L,      21L,      15L,      9L, 
        7L,      4L,      126L,      118L, 
        100L,      65L,      72L,      125L, 
        108L,      61L,      103L,      16L, 
        6L,      125L,      117L,      7L, 
        29L,      0L,      108L,      2L, 
        125L,      120L,      119L,      111L, 
        119L,      1L,      0L,      2L, 
        7L,      10L,      28L,      28L, 
        23L,      35L,      47L,      65L, 
        67L,      79L,      85L,      88L, 
        126L,      2L,      76L,      16L, 
        105L,      44L,      13L,      116L, 
        42L,      116L,      99L,      41L, 
        124L,      94L,      33L,      53L, 
        70L,      36L,      103L,      53L, 
        60L,      60L,      38L,      38L, 
        47L,      71L,      100L,      4L, 
        19L,      24L,      39L,      43L, 
        48L,      27L,      127L,      120L, 
        114L,      104L,      92L,      90L, 
        104L,      124L,      3L,      13L, 
        38L,      65L,      81L,      90L, 
        106L,      108L,      84L,      120L, 
        9L,      69L,      121L,      31L, 
        11L,      46L,      96L,      11L, 
        102L,      127L,      104L,      119L, 
        78L,      70L,      74L,      59L, 
        18L,      91L,      55L,      49L, 
        33L,      11L,      18L,      46L, 
        87L,      126L,      25L,      34L, 
        43L,      63L,      58L,      37L, 
        11L,      121L,      113L,      104L, 
        97L,      92L,      102L,      114L, 
        6L,      22L,      41L,      65L, 
        94L,      109L,      102L,      96L, 
        110L,      23L,      72L,      54L, 
        18L,      23L,      47L,      99L, 
        120L,      92L,      119L,      108L, 
        117L,      65L,      73L,      79L, 
        59L,      11L,      84L,      55L, 
        0L};
long out_data[720]  = 
  {      3L,      4294967290L,      4294967293L,      29L, 
        88L,      137L,      135L,      86L, 
        32L,      7L,      7L,      4L, 
        4294967289L,      0L,      40L,      91L, 
        107L,      79L,      43L,      33L, 
        45L,      48L,      39L,      39L, 
        55L,      71L,      66L,      39L, 
        8L,      4294967284L,      4294967285L,      13L, 
        46L,      59L,      37L,      0L, 
        4294967288L,      29L,      89L,      131L, 
        135L,      111L,      78L,      47L, 
        18L,      4294967295L,      4294967291L,      4L, 
        21L,      35L,      45L,      49L, 
        47L,      41L,      38L,      42L, 
        54L,      72L,      88L,      95L, 
        90L,      79L,      70L,      65L, 
        50L,      27L,      23L,      55L, 
        105L,      123L,      89L,      47L, 
        36L,      48L,      42L,      8L, 
        4294967286L,      7L,      36L,      49L, 
        47L,      51L,      50L,      30L, 
        4L,      7L,      35L,      51L, 
        33L,      14L,      30L,      74L, 
        97L,      75L,      33L,      14L, 
        34L,      73L,      94L,      77L, 
        37L,      11L,      24L,      50L, 
        51L,      21L,      5L,      41L, 
        100L,      118L,      77L,      22L, 
        9L,      38L,      55L,      35L, 
        11L,      21L,      60L,      82L, 
        64L,      35L,      29L,      45L, 
        54L,      45L,      36L,      41L, 
        50L,      44L,      33L,      43L, 
        80L,      123L,      141L,      115L, 
        71L,      34L,      15L,      7L, 
        4294967295L,      0L,      19L,      45L, 
        54L,      43L,      35L,      50L, 
        78L,      92L,      85L,      79L, 
        85L,      92L,      80L,      52L, 
        32L,      34L,      50L,      56L, 
        47L,      37L,      42L,      53L, 
        50L,      35L,      31L,      54L, 
        87L,      96L,      76L,      49L, 
        45L,      64L,      87L,      103L, 
        103L,      76L,      33L,      4L, 
        8L,      32L,      48L,      44L, 
        51L,      78L,      97L,      86L, 
        57L,      38L,      38L,      43L, 
        46L,      56L,      74L,      87L, 
        88L,      92L,      95L,      80L, 
        49L,      29L,      49L,      88L, 
        93L,      55L,      22L,      35L, 
        85L,      113L,      86L,      40L, 
        24L,      48L,      81L,      96L, 
        92L,      82L,      79L,      84L, 
        94L,      98L,      87L,      69L, 
        58L,      53L,      38L,      23L, 
        35L,      71L,      93L,      72L, 
        39L,      48L,      97L,      121L, 
        90L,      49L,      45L,      69L, 
        79L,      65L,      62L,      72L, 
        72L,      58L,      61L,      83L, 
        85L,      47L,      13L,      31L, 
        85L,      105L,      71L,      30L, 
        28L,      50L,      60L,      49L, 
        40L,      45L,      52L,      50L, 
        46L,      46L,      47L,      45L, 
        47L,      50L,      47L,      38L, 
        35L,      48L,      61L,      44L, 
        3L,      4294967279L,      10L,      52L, 
        57L,      24L,      10L,      40L, 
        66L,      40L,      4294967291L,      4294967294L, 
        55L,      97L,      83L,      50L, 
        53L,      75L,      76L,      54L, 
        54L,      78L,      86L,      51L, 
        14L,      27L,      78L,      105L, 
        81L,      34L,      13L,      36L, 
        75L,      94L,      77L,      42L, 
        18L,      22L,      41L,      53L, 
        51L,      42L,      37L,      38L, 
        47L,      56L,      49L,      29L, 
        29L,      66L,      104L,      88L, 
        26L,      4294967295L,      42L,      99L, 
        95L,      39L,      10L,      34L, 
        52L,      30L,      11L,      39L, 
        88L,      90L,      46L,      16L, 
        27L,      40L,      35L,      49L, 
        96L,      124L,      86L,      27L, 
        29L,      93L,      129L,      92L, 
        41L,      44L,      78L,      81L, 
        53L,      51L,      77L,      83L, 
        50L,      36L,      80L,      134L, 
        133L,      90L,      70L,      93L, 
        107L,      91L,      79L,      99L, 
        113L,      84L,      42L,      44L, 
        80L,      86L,      48L,      30L, 
        77L,      141L,      144L,      91L, 
        58L,      85L,      128L,      137L, 
        120L,      123L,      138L,      125L, 
        83L,      62L,      91L,      131L, 
        127L,      89L,      74L,      91L, 
        94L,      46L,      4294967284L,      4294967283L, 
        45L,      95L,      97L,      80L, 
        84L,      94L,      80L,      48L, 
        38L,      52L,      50L,      24L, 
        9L,      39L,      91L,      116L, 
        109L,      94L,      82L,      64L, 
        45L,      52L,      84L,      92L, 
        49L,      0L,      10L,      86L, 
        156L,      150L,      89L,      46L, 
        56L,      87L,      94L,      75L, 
        70L,      94L,      120L,      124L, 
        119L,      128L,      141L,      125L, 
        79L,      43L,      43L,      51L, 
        30L,      0L,      6L,      40L, 
        55L,      29L,      9L,      36L, 
        83L,      93L,      61L,      31L, 
        33L,      41L,      24L,      4294967292L, 
        4294967285L,      6L,      18L,      9L, 
        4294967293L,      1L,      15L,      12L, 
        4294967290L,      4294967282L,      9L,      50L, 
        77L,      86L,      92L,      98L, 
        83L,      39L,      0L,      4294967292L, 
        12L,      8L,      4294967280L,      4294967289L, 
        54L,      106L,      85L,      28L, 
        27L,      96L,      142L,      97L, 
        21L,      20L,      94L,      140L, 
        97L,      29L,      26L,      82L, 
        107L,      61L,      4294967291L,      4294967272L, 
        1L,      21L,      12L,      4294967294L, 
        0L,      13L,      17L,      9L, 
        1L,      1L,      7L,      12L, 
        11L,      7L,      6L,      13L, 
        22L,      23L,      16L,      12L, 
        19L,      28L,      19L,      0L, 
        0L,      38L,      95L,      123L, 
        104L,      72L,      72L,      104L, 
        125L,      96L,      45L,      25L, 
        55L,      92L,      90L,      49L, 
        15L,      19L,      49L,      76L, 
        94L,      113L,      131L,      127L, 
        88L,      32L,      4294967293L,      4294967288L, 
        9L,      24L,      25L,      22L, 
        25L,      39L,      55L,      61L, 
        66L,      79L,      98L,      101L, 
        79L,      51L,      44L,      54L, 
        61L,      56L,      52L,      64L, 
        84L,      93L,      91L,      88L, 
        89L,      83L,      65L,      50L, 
        51L,      63L,      74L,      75L, 
        67L,      51L,      37L,      40L, 
        61L,      79L,      68L,      35L, 
        14L,      22L,      41L,      44L, 
        40L,      57L,      99L,      132L, 
        125L,      95L,      86L,      105L, 
        115L,      86L,      36L,      12L, 
        30L,      64L,      86L,      96L, 
        105L,      110L,      99L,      78L, 
        66L,      68L,      71L,      59L, 
        42L,      34L,      45L,      69L, 
        93L,      112L,      119L,      109L, 
        91L,      74L,      63L,      55L, 
        50L,      57L,      67L,      61L, 
        32L,      5L,      16L,      63L, 
        100L,      90L,      52L,      33L, 
        46L,      62L,      51L,      34L, 
        48L,      89L,      117L,      113L, 
        96L,      97L,      103L,      85L, 
        45L,      18L,      29L,      67L, 
        101L,      113L,      108L,      95L, 
        83L,      71L,      57L,      41L, 
        28L,      30L,      53L,      86L, 
        111L,      116L,      111L,      106L, 
        102L,      92L,      75L,      58L, 
        51L,      54L,      56L,      44L, 
        0L};
void fir_filter_int(long *in , long *out , long in_len , long *coef , long coef_len ,
                    long scale ) ;
int main(void) 
{ 
  long *output ;
  unsigned long __lengthofoutput ;
  void *tmp ;
  int cptr_main_1  = 0;

  {
  cptr_main_1 ++;
  __lengthofoutput = 0UL;
  tmp = __builtin_alloca(sizeof(*output) * __lengthofoutput);
  output = (long *)tmp;
  fir_filter_int(in_data, output, 700L, fir_int, 35L, 285L);
  return (0);
}
}
void fir_filter_int(long *in , long *out , long in_len , long *coef , long coef_len ,
                    long scale ) 
{ 
  long i ;
  long j ;
  long coef_len2 ;
  long acc_length ;
  long acc ;
  long *in_ptr ;
  long *data_ptr ;
  long *coef_start ;
  long *coef_ptr ;
  long *in_end ;
  long *tmp ;
  long *tmp___0 ;
  long *tmp___1 ;
  long *tmp___2 ;
  long *tmp___3 ;
  int cptr_fir_filter_int_1  = 0;
  int cptr_fir_filter_int_2  = 0;
  int cptr_fir_filter_int_3  = 0;
  int cptr_fir_filter_int_4  = 0;
  int cptr_fir_filter_int_5  = 0;
  int cptr_fir_filter_int_6  = 0;
  int cptr_fir_filter_int_7  = 0;

  {
  cptr_fir_filter_int_1 ++;
  coef_start = coef;
  coef_len2 = (coef_len + 1L) >> 1;
  in_end = (in + in_len) - 1;
  in_ptr = (in + coef_len2) - 1;
  acc_length = coef_len2;
  i = 0L;
  while (i < in_len) {
    cptr_fir_filter_int_2 ++;
    data_ptr = in_ptr;
    coef_ptr = coef_start;
    tmp = coef_ptr;
    coef_ptr ++;
    tmp___0 = data_ptr;
    data_ptr --;
    acc = *tmp * *tmp___0;
    j = 1L;
    while (j < acc_length) {
      cptr_fir_filter_int_3 ++;
      tmp___1 = coef_ptr;
      coef_ptr ++;
      tmp___2 = data_ptr;
      data_ptr --;
      acc += *tmp___1 * *tmp___2;
      j ++;
    }
    tmp___3 = out;
    out ++;
    *tmp___3 = (long )((int )(acc / scale));
    if ((unsigned long )in_ptr == (unsigned long )in_end) {
      cptr_fir_filter_int_4 ++;
      acc_length --;
      coef_start ++;
    } else {
      if (acc_length < coef_len) {
        cptr_fir_filter_int_5 ++;
        acc_length ++;
      }
      cptr_fir_filter_int_6 ++;
      in_ptr ++;
    }
    cptr_fir_filter_int_7 ++;
    i ++;
  }
  return;
}
}
