/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
double a[3]  ;
double x1[2]  ;
double x2[2]  ;
int flag  ;
int qurt(void) ;
double qurt_fabs(double n ) 
{ 
  double f ;
  int cptr_qurt_fabs_1 ;
  int cptr_qurt_fabs_2 ;

  {
  cptr_qurt_fabs_1 = 0;
  cptr_qurt_fabs_2 = 0;
  if (n >= (double )0) {
    cptr_qurt_fabs_1 ++;
    f = n;
  } else {
    cptr_qurt_fabs_2 ++;
    f = - n;
  }
  return (f);
}
}
double qurt_sqrt(double val ) 
{ 
  double x ;
  double dx ;
  double diff ;
  double min_tol ;
  int i ;
  int flag___0 ;
  double tmp ;
  int cptr_qurt_sqrt_1 ;
  int cptr_qurt_sqrt_2 ;
  int cptr_qurt_sqrt_3 ;
  int cptr_qurt_sqrt_4 ;
  int cptr_qurt_sqrt_5 ;
  int cptr_qurt_sqrt_6 ;
  double n15 ;
  double f16 ;
  int cptr_qurt_fabs_117 ;
  int cptr_qurt_fabs_218 ;
  double ret_qurt_fabs19 ;

  {
  cptr_qurt_sqrt_1 = 0;
  cptr_qurt_sqrt_2 = 0;
  cptr_qurt_sqrt_3 = 0;
  cptr_qurt_sqrt_4 = 0;
  cptr_qurt_sqrt_5 = 0;
  cptr_qurt_sqrt_6 = 0;
  cptr_qurt_sqrt_1 ++;
  x = val / (double )10;
  min_tol = 0.00001;
  flag___0 = 0;
  if (val == (double )0) {
    cptr_qurt_sqrt_2 ++;
    x = (double )0;
  } else {
    cptr_qurt_sqrt_3 ++;
    i = 1;
    while (i < 20) {
      if (! flag___0) {
        {
        cptr_qurt_sqrt_4 ++;
        dx = (val - x * x) / (2.0 * x);
        x += dx;
        diff = val - x * x;
        n15 = diff;
        {
        cptr_qurt_fabs_117 = 0;
        cptr_qurt_fabs_218 = 0;
        if (n15 >= (double )0) {
          cptr_qurt_fabs_117 ++;
          f16 = n15;
        } else {
          cptr_qurt_fabs_218 ++;
          f16 = - n15;
        }
        {
        ret_qurt_fabs19 = f16;
        goto Lret_qurt_fabs;
        }
        }
        Lret_qurt_fabs: /* CIL Label */ 
        tmp = ret_qurt_fabs19;
        }
        if (tmp <= min_tol) {
          cptr_qurt_sqrt_5 ++;
          flag___0 = 1;
        }
      }
      cptr_qurt_sqrt_6 ++;
      i ++;
    }
  }
  return (x);
}
}
int main(void) 
{ 
  int cptr_main_1 ;
  double d2 ;
  double w13 ;
  double w24 ;
  double tmp5 ;
  int cptr_qurt_16 ;
  int cptr_qurt_27 ;
  int cptr_qurt_38 ;
  int cptr_qurt_49 ;
  double n910 ;
  double f1011 ;
  int cptr_qurt_fabs_11112 ;
  int cptr_qurt_fabs_21213 ;
  double ret_qurt_fabs1314 ;
  double val1415 ;
  double x1516 ;
  double dx1617 ;
  double diff1718 ;
  double min_tol1819 ;
  int i1920 ;
  int flag___02021 ;
  double tmp2122 ;
  int cptr_qurt_sqrt_12223 ;
  int cptr_qurt_sqrt_22324 ;
  int cptr_qurt_sqrt_32425 ;
  int cptr_qurt_sqrt_42526 ;
  int cptr_qurt_sqrt_52627 ;
  int cptr_qurt_sqrt_62728 ;
  double n152829 ;
  double f162930 ;
  int cptr_qurt_fabs_1173031 ;
  int cptr_qurt_fabs_2183132 ;
  double ret_qurt_fabs193233 ;
  double ret_qurt_sqrt3334 ;
  double d35 ;
  double w136 ;
  double w237 ;
  double tmp38 ;
  int cptr_qurt_139 ;
  int cptr_qurt_240 ;
  int cptr_qurt_341 ;
  int cptr_qurt_442 ;
  double n943 ;
  double f1044 ;
  int cptr_qurt_fabs_11145 ;
  int cptr_qurt_fabs_21246 ;
  double ret_qurt_fabs1347 ;
  double val1448 ;
  double x1549 ;
  double dx1650 ;
  double diff1751 ;
  double min_tol1852 ;
  int i1953 ;
  int flag___02054 ;
  double tmp2155 ;
  int cptr_qurt_sqrt_12256 ;
  int cptr_qurt_sqrt_22357 ;
  int cptr_qurt_sqrt_32458 ;
  int cptr_qurt_sqrt_42559 ;
  int cptr_qurt_sqrt_52660 ;
  int cptr_qurt_sqrt_62761 ;
  double n152862 ;
  double f162963 ;
  int cptr_qurt_fabs_1173064 ;
  int cptr_qurt_fabs_2183165 ;
  double ret_qurt_fabs193266 ;
  double ret_qurt_sqrt3367 ;
  double d68 ;
  double w169 ;
  double w270 ;
  double tmp71 ;
  int cptr_qurt_172 ;
  int cptr_qurt_273 ;
  int cptr_qurt_374 ;
  int cptr_qurt_475 ;
  double n976 ;
  double f1077 ;
  int cptr_qurt_fabs_11178 ;
  int cptr_qurt_fabs_21279 ;
  double ret_qurt_fabs1380 ;
  double val1481 ;
  double x1582 ;
  double dx1683 ;
  double diff1784 ;
  double min_tol1885 ;
  int i1986 ;
  int flag___02087 ;
  double tmp2188 ;
  int cptr_qurt_sqrt_12289 ;
  int cptr_qurt_sqrt_22390 ;
  int cptr_qurt_sqrt_32491 ;
  int cptr_qurt_sqrt_42592 ;
  int cptr_qurt_sqrt_52693 ;
  int cptr_qurt_sqrt_62794 ;
  double n152895 ;
  double f162996 ;
  int cptr_qurt_fabs_1173097 ;
  int cptr_qurt_fabs_2183198 ;
  double ret_qurt_fabs193299 ;
  double ret_qurt_sqrt33100 ;

  {
  {
  cptr_main_1 = 0;
  cptr_main_1 ++;
  a[0] = 1.0;
  a[1] = - 3.0;
  a[2] = 2.0;
  {
  cptr_qurt_16 = 0;
  cptr_qurt_27 = 0;
  cptr_qurt_38 = 0;
  cptr_qurt_49 = 0;
  if (a[0] == 0.0) {
    goto Lret_qurt;
  }
  {
  cptr_qurt_16 ++;
  d2 = a[1] * a[1] - ((double )4 * a[0]) * a[2];
  w13 = 2.0 * a[0];
  n910 = d2;
  {
  cptr_qurt_fabs_11112 = 0;
  cptr_qurt_fabs_21213 = 0;
  if (n910 >= (double )0) {
    cptr_qurt_fabs_11112 ++;
    f1011 = n910;
  } else {
    cptr_qurt_fabs_21213 ++;
    f1011 = - n910;
  }
  {
  ret_qurt_fabs1314 = f1011;
  goto Lret_qurt_fabs;
  }
  }
  Lret_qurt_fabs: /* CIL Label */ 
  tmp5 = ret_qurt_fabs1314;
  val1415 = tmp5;
  {
  cptr_qurt_sqrt_12223 = 0;
  cptr_qurt_sqrt_22324 = 0;
  cptr_qurt_sqrt_32425 = 0;
  cptr_qurt_sqrt_42526 = 0;
  cptr_qurt_sqrt_52627 = 0;
  cptr_qurt_sqrt_62728 = 0;
  cptr_qurt_sqrt_12223 ++;
  x1516 = val1415 / (double )10;
  min_tol1819 = 0.00001;
  flag___02021 = 0;
  if (val1415 == (double )0) {
    cptr_qurt_sqrt_22324 ++;
    x1516 = (double )0;
  } else {
    cptr_qurt_sqrt_32425 ++;
    i1920 = 1;
    while (i1920 < 20) {
      if (! flag___02021) {
        {
        cptr_qurt_sqrt_42526 ++;
        dx1617 = (val1415 - x1516 * x1516) / (2.0 * x1516);
        x1516 += dx1617;
        diff1718 = val1415 - x1516 * x1516;
        n152829 = diff1718;
        {
        cptr_qurt_fabs_1173031 = 0;
        cptr_qurt_fabs_2183132 = 0;
        if (n152829 >= (double )0) {
          cptr_qurt_fabs_1173031 ++;
          f162930 = n152829;
        } else {
          cptr_qurt_fabs_2183132 ++;
          f162930 = - n152829;
        }
        {
        ret_qurt_fabs193233 = f162930;
        goto Lret_qurt_fabs___0;
        }
        }
        Lret_qurt_fabs___0: /* CIL Label */ 
        tmp2122 = ret_qurt_fabs193233;
        }
        if (tmp2122 <= min_tol1819) {
          cptr_qurt_sqrt_52627 ++;
          flag___02021 = 1;
        }
      }
      cptr_qurt_sqrt_62728 ++;
      i1920 ++;
    }
  }
  {
  ret_qurt_sqrt3334 = x1516;
  goto Lret_qurt_sqrt;
  }
  }
  Lret_qurt_sqrt: /* CIL Label */ 
  w24 = ret_qurt_sqrt3334;
  }
  if (d2 > 0.0) {
    cptr_qurt_27 ++;
    flag = 1;
    x1[0] = (- a[1] + w24) / w13;
    x1[1] = 0.0;
    x2[0] = (- a[1] - w24) / w13;
    x2[1] = 0.0;
    goto Lret_qurt;
  } else
  if (d2 == 0.0) {
    cptr_qurt_38 ++;
    flag = 0;
    x1[0] = - a[1] / w13;
    x1[1] = 0.0;
    x2[0] = x1[0];
    x2[1] = 0.0;
    goto Lret_qurt;
  } else {
    cptr_qurt_49 ++;
    flag = -1;
    w24 /= w13;
    x1[0] = - a[1] / w13;
    x1[1] = w24;
    x2[0] = x1[0];
    x2[1] = - w24;
    goto Lret_qurt;
  }
  }
  Lret_qurt: /* CIL Label */ ;
  a[0] = 1.0;
  a[1] = - 2.0;
  a[2] = 1.0;
  {
  cptr_qurt_139 = 0;
  cptr_qurt_240 = 0;
  cptr_qurt_341 = 0;
  cptr_qurt_442 = 0;
  if (a[0] == 0.0) {
    goto Lret_qurt___0;
  }
  {
  cptr_qurt_139 ++;
  d35 = a[1] * a[1] - ((double )4 * a[0]) * a[2];
  w136 = 2.0 * a[0];
  n943 = d35;
  {
  cptr_qurt_fabs_11145 = 0;
  cptr_qurt_fabs_21246 = 0;
  if (n943 >= (double )0) {
    cptr_qurt_fabs_11145 ++;
    f1044 = n943;
  } else {
    cptr_qurt_fabs_21246 ++;
    f1044 = - n943;
  }
  {
  ret_qurt_fabs1347 = f1044;
  goto Lret_qurt_fabs___1;
  }
  }
  Lret_qurt_fabs___1: /* CIL Label */ 
  tmp38 = ret_qurt_fabs1347;
  val1448 = tmp38;
  {
  cptr_qurt_sqrt_12256 = 0;
  cptr_qurt_sqrt_22357 = 0;
  cptr_qurt_sqrt_32458 = 0;
  cptr_qurt_sqrt_42559 = 0;
  cptr_qurt_sqrt_52660 = 0;
  cptr_qurt_sqrt_62761 = 0;
  cptr_qurt_sqrt_12256 ++;
  x1549 = val1448 / (double )10;
  min_tol1852 = 0.00001;
  flag___02054 = 0;
  if (val1448 == (double )0) {
    cptr_qurt_sqrt_22357 ++;
    x1549 = (double )0;
  } else {
    cptr_qurt_sqrt_32458 ++;
    i1953 = 1;
    while (i1953 < 20) {
      if (! flag___02054) {
        {
        cptr_qurt_sqrt_42559 ++;
        dx1650 = (val1448 - x1549 * x1549) / (2.0 * x1549);
        x1549 += dx1650;
        diff1751 = val1448 - x1549 * x1549;
        n152862 = diff1751;
        {
        cptr_qurt_fabs_1173064 = 0;
        cptr_qurt_fabs_2183165 = 0;
        if (n152862 >= (double )0) {
          cptr_qurt_fabs_1173064 ++;
          f162963 = n152862;
        } else {
          cptr_qurt_fabs_2183165 ++;
          f162963 = - n152862;
        }
        {
        ret_qurt_fabs193266 = f162963;
        goto Lret_qurt_fabs___2;
        }
        }
        Lret_qurt_fabs___2: /* CIL Label */ 
        tmp2155 = ret_qurt_fabs193266;
        }
        if (tmp2155 <= min_tol1852) {
          cptr_qurt_sqrt_52660 ++;
          flag___02054 = 1;
        }
      }
      cptr_qurt_sqrt_62761 ++;
      i1953 ++;
    }
  }
  {
  ret_qurt_sqrt3367 = x1549;
  goto Lret_qurt_sqrt___0;
  }
  }
  Lret_qurt_sqrt___0: /* CIL Label */ 
  w237 = ret_qurt_sqrt3367;
  }
  if (d35 > 0.0) {
    cptr_qurt_240 ++;
    flag = 1;
    x1[0] = (- a[1] + w237) / w136;
    x1[1] = 0.0;
    x2[0] = (- a[1] - w237) / w136;
    x2[1] = 0.0;
    goto Lret_qurt___0;
  } else
  if (d35 == 0.0) {
    cptr_qurt_341 ++;
    flag = 0;
    x1[0] = - a[1] / w136;
    x1[1] = 0.0;
    x2[0] = x1[0];
    x2[1] = 0.0;
    goto Lret_qurt___0;
  } else {
    cptr_qurt_442 ++;
    flag = -1;
    w237 /= w136;
    x1[0] = - a[1] / w136;
    x1[1] = w237;
    x2[0] = x1[0];
    x2[1] = - w237;
    goto Lret_qurt___0;
  }
  }
  Lret_qurt___0: /* CIL Label */ ;
  a[0] = 1.0;
  a[1] = - 4.0;
  a[2] = 8.0;
  {
  cptr_qurt_172 = 0;
  cptr_qurt_273 = 0;
  cptr_qurt_374 = 0;
  cptr_qurt_475 = 0;
  if (a[0] == 0.0) {
    goto Lret_qurt___1;
  }
  {
  cptr_qurt_172 ++;
  d68 = a[1] * a[1] - ((double )4 * a[0]) * a[2];
  w169 = 2.0 * a[0];
  n976 = d68;
  {
  cptr_qurt_fabs_11178 = 0;
  cptr_qurt_fabs_21279 = 0;
  if (n976 >= (double )0) {
    cptr_qurt_fabs_11178 ++;
    f1077 = n976;
  } else {
    cptr_qurt_fabs_21279 ++;
    f1077 = - n976;
  }
  {
  ret_qurt_fabs1380 = f1077;
  goto Lret_qurt_fabs___3;
  }
  }
  Lret_qurt_fabs___3: /* CIL Label */ 
  tmp71 = ret_qurt_fabs1380;
  val1481 = tmp71;
  {
  cptr_qurt_sqrt_12289 = 0;
  cptr_qurt_sqrt_22390 = 0;
  cptr_qurt_sqrt_32491 = 0;
  cptr_qurt_sqrt_42592 = 0;
  cptr_qurt_sqrt_52693 = 0;
  cptr_qurt_sqrt_62794 = 0;
  cptr_qurt_sqrt_12289 ++;
  x1582 = val1481 / (double )10;
  min_tol1885 = 0.00001;
  flag___02087 = 0;
  if (val1481 == (double )0) {
    cptr_qurt_sqrt_22390 ++;
    x1582 = (double )0;
  } else {
    cptr_qurt_sqrt_32491 ++;
    i1986 = 1;
    while (i1986 < 20) {
      if (! flag___02087) {
        {
        cptr_qurt_sqrt_42592 ++;
        dx1683 = (val1481 - x1582 * x1582) / (2.0 * x1582);
        x1582 += dx1683;
        diff1784 = val1481 - x1582 * x1582;
        n152895 = diff1784;
        {
        cptr_qurt_fabs_1173097 = 0;
        cptr_qurt_fabs_2183198 = 0;
        if (n152895 >= (double )0) {
          cptr_qurt_fabs_1173097 ++;
          f162996 = n152895;
        } else {
          cptr_qurt_fabs_2183198 ++;
          f162996 = - n152895;
        }
        {
        ret_qurt_fabs193299 = f162996;
        goto Lret_qurt_fabs___4;
        }
        }
        Lret_qurt_fabs___4: /* CIL Label */ 
        tmp2188 = ret_qurt_fabs193299;
        }
        if (tmp2188 <= min_tol1885) {
          cptr_qurt_sqrt_52693 ++;
          flag___02087 = 1;
        }
      }
      cptr_qurt_sqrt_62794 ++;
      i1986 ++;
    }
  }
  {
  ret_qurt_sqrt33100 = x1582;
  goto Lret_qurt_sqrt___1;
  }
  }
  Lret_qurt_sqrt___1: /* CIL Label */ 
  w270 = ret_qurt_sqrt33100;
  }
  if (d68 > 0.0) {
    cptr_qurt_273 ++;
    flag = 1;
    x1[0] = (- a[1] + w270) / w169;
    x1[1] = 0.0;
    x2[0] = (- a[1] - w270) / w169;
    x2[1] = 0.0;
    goto Lret_qurt___1;
  } else
  if (d68 == 0.0) {
    cptr_qurt_374 ++;
    flag = 0;
    x1[0] = - a[1] / w169;
    x1[1] = 0.0;
    x2[0] = x1[0];
    x2[1] = 0.0;
    goto Lret_qurt___1;
  } else {
    cptr_qurt_475 ++;
    flag = -1;
    w270 /= w169;
    x1[0] = - a[1] / w169;
    x1[1] = w270;
    x2[0] = x1[0];
    x2[1] = - w270;
    goto Lret_qurt___1;
  }
  }
  Lret_qurt___1: /* CIL Label */ ;
  }
  return (0);
}
}
int qurt(void) 
{ 
  double d ;
  double w1 ;
  double w2 ;
  double tmp ;
  int cptr_qurt_1 ;
  int cptr_qurt_2 ;
  int cptr_qurt_3 ;
  int cptr_qurt_4 ;
  double n9 ;
  double f10 ;
  int cptr_qurt_fabs_111 ;
  int cptr_qurt_fabs_212 ;
  double ret_qurt_fabs13 ;
  double val14 ;
  double x15 ;
  double dx16 ;
  double diff17 ;
  double min_tol18 ;
  int i19 ;
  int flag___020 ;
  double tmp21 ;
  int cptr_qurt_sqrt_122 ;
  int cptr_qurt_sqrt_223 ;
  int cptr_qurt_sqrt_324 ;
  int cptr_qurt_sqrt_425 ;
  int cptr_qurt_sqrt_526 ;
  int cptr_qurt_sqrt_627 ;
  double n1528 ;
  double f1629 ;
  int cptr_qurt_fabs_11730 ;
  int cptr_qurt_fabs_21831 ;
  double ret_qurt_fabs1932 ;
  double ret_qurt_sqrt33 ;

  {
  cptr_qurt_1 = 0;
  cptr_qurt_2 = 0;
  cptr_qurt_3 = 0;
  cptr_qurt_4 = 0;
  if (a[0] == 0.0) {
    return (999);
  }
  {
  cptr_qurt_1 ++;
  d = a[1] * a[1] - ((double )4 * a[0]) * a[2];
  w1 = 2.0 * a[0];
  n9 = d;
  {
  cptr_qurt_fabs_111 = 0;
  cptr_qurt_fabs_212 = 0;
  if (n9 >= (double )0) {
    cptr_qurt_fabs_111 ++;
    f10 = n9;
  } else {
    cptr_qurt_fabs_212 ++;
    f10 = - n9;
  }
  {
  ret_qurt_fabs13 = f10;
  goto Lret_qurt_fabs;
  }
  }
  Lret_qurt_fabs: /* CIL Label */ 
  tmp = ret_qurt_fabs13;
  val14 = tmp;
  {
  cptr_qurt_sqrt_122 = 0;
  cptr_qurt_sqrt_223 = 0;
  cptr_qurt_sqrt_324 = 0;
  cptr_qurt_sqrt_425 = 0;
  cptr_qurt_sqrt_526 = 0;
  cptr_qurt_sqrt_627 = 0;
  cptr_qurt_sqrt_122 ++;
  x15 = val14 / (double )10;
  min_tol18 = 0.00001;
  flag___020 = 0;
  if (val14 == (double )0) {
    cptr_qurt_sqrt_223 ++;
    x15 = (double )0;
  } else {
    cptr_qurt_sqrt_324 ++;
    i19 = 1;
    while (i19 < 20) {
      if (! flag___020) {
        {
        cptr_qurt_sqrt_425 ++;
        dx16 = (val14 - x15 * x15) / (2.0 * x15);
        x15 += dx16;
        diff17 = val14 - x15 * x15;
        n1528 = diff17;
        {
        cptr_qurt_fabs_11730 = 0;
        cptr_qurt_fabs_21831 = 0;
        if (n1528 >= (double )0) {
          cptr_qurt_fabs_11730 ++;
          f1629 = n1528;
        } else {
          cptr_qurt_fabs_21831 ++;
          f1629 = - n1528;
        }
        {
        ret_qurt_fabs1932 = f1629;
        goto Lret_qurt_fabs___0;
        }
        }
        Lret_qurt_fabs___0: /* CIL Label */ 
        tmp21 = ret_qurt_fabs1932;
        }
        if (tmp21 <= min_tol18) {
          cptr_qurt_sqrt_526 ++;
          flag___020 = 1;
        }
      }
      cptr_qurt_sqrt_627 ++;
      i19 ++;
    }
  }
  {
  ret_qurt_sqrt33 = x15;
  goto Lret_qurt_sqrt;
  }
  }
  Lret_qurt_sqrt: /* CIL Label */ 
  w2 = ret_qurt_sqrt33;
  }
  if (d > 0.0) {
    cptr_qurt_2 ++;
    flag = 1;
    x1[0] = (- a[1] + w2) / w1;
    x1[1] = 0.0;
    x2[0] = (- a[1] - w2) / w1;
    x2[1] = 0.0;
    return (0);
  } else
  if (d == 0.0) {
    cptr_qurt_3 ++;
    flag = 0;
    x1[0] = - a[1] / w1;
    x1[1] = 0.0;
    x2[0] = x1[0];
    x2[1] = 0.0;
    return (0);
  } else {
    cptr_qurt_4 ++;
    flag = -1;
    w2 /= w1;
    x1[0] = - a[1] / w1;
    x1[1] = w2;
    x2[0] = x1[0];
    x2[1] = - w2;
    return (0);
  }
}
}
