/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern void cptr_dummy_func(int x ) ;
int data[64]  ;
void jpeg_fdct_islow(void) 
{ 
  int tmp0 ;
  int tmp1 ;
  int tmp2 ;
  int tmp3 ;
  int tmp4 ;
  int tmp5 ;
  int tmp6 ;
  int tmp7 ;
  int tmp10 ;
  int tmp11 ;
  int tmp12 ;
  int tmp13 ;
  int z1 ;
  int z2 ;
  int z3 ;
  int z4 ;
  int z5 ;
  int *dataptr ;
  int ctr ;
  int cptr_jpeg_fdct_islow_1 ;
  int cptr_jpeg_fdct_islow_2 ;
  int cptr_jpeg_fdct_islow_3 ;

  {
  cptr_jpeg_fdct_islow_1 = 0;
  cptr_jpeg_fdct_islow_2 = 0;
  cptr_jpeg_fdct_islow_3 = 0;
  cptr_jpeg_fdct_islow_1 ++;
  dataptr = data;
  ctr = 7;
  while (ctr >= 0) {
    cptr_jpeg_fdct_islow_2 ++;
    tmp0 = *(dataptr + 0) + *(dataptr + 7);
    tmp7 = *(dataptr + 0) - *(dataptr + 7);
    tmp1 = *(dataptr + 1) + *(dataptr + 6);
    tmp6 = *(dataptr + 1) - *(dataptr + 6);
    tmp2 = *(dataptr + 2) + *(dataptr + 5);
    tmp5 = *(dataptr + 2) - *(dataptr + 5);
    tmp3 = *(dataptr + 3) + *(dataptr + 4);
    tmp4 = *(dataptr + 3) - *(dataptr + 4);
    tmp10 = tmp0 + tmp3;
    tmp13 = tmp0 - tmp3;
    tmp11 = tmp1 + tmp2;
    tmp12 = tmp1 - tmp2;
    *(dataptr + 0) = (tmp10 + tmp11) << 2;
    *(dataptr + 4) = (tmp10 - tmp11) << 2;
    z1 = (tmp12 + tmp13) * 4433;
    *(dataptr + 2) = ((z1 + tmp13 * 6270) + (1 << 10)) >> 11;
    *(dataptr + 6) = ((z1 + tmp12 * -15137) + (1 << 10)) >> 11;
    z1 = tmp4 + tmp7;
    z2 = tmp5 + tmp6;
    z3 = tmp4 + tmp6;
    z4 = tmp5 + tmp7;
    z5 = (z3 + z4) * 9633;
    tmp4 *= 2446;
    tmp5 *= 16819;
    tmp6 *= 25172;
    tmp7 *= 12299;
    z1 *= -7373;
    z2 *= -20995;
    z3 *= -16069;
    z4 *= -3196;
    z3 += z5;
    z4 += z5;
    *(dataptr + 7) = (((tmp4 + z1) + z3) + (1 << 10)) >> 11;
    *(dataptr + 5) = (((tmp5 + z2) + z4) + (1 << 10)) >> 11;
    *(dataptr + 3) = (((tmp6 + z2) + z3) + (1 << 10)) >> 11;
    *(dataptr + 1) = (((tmp7 + z1) + z4) + (1 << 10)) >> 11;
    dataptr += 8;
    ctr --;
  }
  dataptr = data;
  ctr = 7;
  while (ctr >= 0) {
    cptr_jpeg_fdct_islow_3 ++;
    tmp0 = *(dataptr + 0) + *(dataptr + 56);
    tmp7 = *(dataptr + 0) - *(dataptr + 56);
    tmp1 = *(dataptr + 8) + *(dataptr + 48);
    tmp6 = *(dataptr + 8) - *(dataptr + 48);
    tmp2 = *(dataptr + 16) + *(dataptr + 40);
    tmp5 = *(dataptr + 16) - *(dataptr + 40);
    tmp3 = *(dataptr + 24) + *(dataptr + 32);
    tmp4 = *(dataptr + 24) - *(dataptr + 32);
    tmp10 = tmp0 + tmp3;
    tmp13 = tmp0 - tmp3;
    tmp11 = tmp1 + tmp2;
    tmp12 = tmp1 - tmp2;
    *(dataptr + 0) = ((tmp10 + tmp11) + (1 << 1)) >> 2;
    *(dataptr + 32) = ((tmp10 - tmp11) + (1 << 1)) >> 2;
    z1 = (tmp12 + tmp13) * 4433;
    *(dataptr + 16) = ((z1 + tmp13 * 6270) + (1 << 14)) >> 15;
    *(dataptr + 48) = ((z1 + tmp12 * -15137) + (1 << 14)) >> 15;
    z1 = tmp4 + tmp7;
    z2 = tmp5 + tmp6;
    z3 = tmp4 + tmp6;
    z4 = tmp5 + tmp7;
    z5 = (z3 + z4) * 9633;
    tmp4 *= 2446;
    tmp5 *= 16819;
    tmp6 *= 25172;
    tmp7 *= 12299;
    z1 *= -7373;
    z2 *= -20995;
    z3 *= -16069;
    z4 *= -3196;
    z3 += z5;
    z4 += z5;
    *(dataptr + 56) = (((tmp4 + z1) + z3) + (1 << 14)) >> 15;
    *(dataptr + 40) = (((tmp5 + z2) + z4) + (1 << 14)) >> 15;
    *(dataptr + 24) = (((tmp6 + z2) + z3) + (1 << 14)) >> 15;
    *(dataptr + 8) = (((tmp7 + z1) + z4) + (1 << 14)) >> 15;
    dataptr ++;
    ctr --;
  }
  return;
}
}
void main(void) 
{ 
  int i ;
  int seed ;
  int cptr_main_1 ;
  int cptr_main_2 ;
  int tmp05 ;
  int tmp16 ;
  int tmp27 ;
  int tmp38 ;
  int tmp49 ;
  int tmp510 ;
  int tmp611 ;
  int tmp712 ;
  int tmp1013 ;
  int tmp1114 ;
  int tmp1215 ;
  int tmp1316 ;
  int z117 ;
  int z218 ;
  int z319 ;
  int z420 ;
  int z521 ;
  int *dataptr22 ;
  int ctr23 ;
  int cptr_jpeg_fdct_islow_124 ;
  int cptr_jpeg_fdct_islow_225 ;
  int cptr_jpeg_fdct_islow_326 ;

  {
  cptr_main_1 = 0;
  cptr_main_2 = 0;
  cptr_main_1 ++;
  seed = 1;
  i = 0;
  while (i < 64) {
    cptr_main_2 ++;
    seed = (seed * 133 + 81) % 65535;
    data[i] = seed;
    i ++;
  }
  {
  {
  cptr_jpeg_fdct_islow_124 = 0;
  cptr_jpeg_fdct_islow_225 = 0;
  cptr_jpeg_fdct_islow_326 = 0;
  cptr_jpeg_fdct_islow_124 ++;
  dataptr22 = data;
  ctr23 = 7;
  while (ctr23 >= 0) {
    cptr_jpeg_fdct_islow_225 ++;
    tmp05 = *(dataptr22 + 0) + *(dataptr22 + 7);
    tmp712 = *(dataptr22 + 0) - *(dataptr22 + 7);
    tmp16 = *(dataptr22 + 1) + *(dataptr22 + 6);
    tmp611 = *(dataptr22 + 1) - *(dataptr22 + 6);
    tmp27 = *(dataptr22 + 2) + *(dataptr22 + 5);
    tmp510 = *(dataptr22 + 2) - *(dataptr22 + 5);
    tmp38 = *(dataptr22 + 3) + *(dataptr22 + 4);
    tmp49 = *(dataptr22 + 3) - *(dataptr22 + 4);
    tmp1013 = tmp05 + tmp38;
    tmp1316 = tmp05 - tmp38;
    tmp1114 = tmp16 + tmp27;
    tmp1215 = tmp16 - tmp27;
    *(dataptr22 + 0) = (tmp1013 + tmp1114) << 2;
    *(dataptr22 + 4) = (tmp1013 - tmp1114) << 2;
    z117 = (tmp1215 + tmp1316) * 4433;
    *(dataptr22 + 2) = ((z117 + tmp1316 * 6270) + (1 << 10)) >> 11;
    *(dataptr22 + 6) = ((z117 + tmp1215 * -15137) + (1 << 10)) >> 11;
    z117 = tmp49 + tmp712;
    z218 = tmp510 + tmp611;
    z319 = tmp49 + tmp611;
    z420 = tmp510 + tmp712;
    z521 = (z319 + z420) * 9633;
    tmp49 *= 2446;
    tmp510 *= 16819;
    tmp611 *= 25172;
    tmp712 *= 12299;
    z117 *= -7373;
    z218 *= -20995;
    z319 *= -16069;
    z420 *= -3196;
    z319 += z521;
    z420 += z521;
    *(dataptr22 + 7) = (((tmp49 + z117) + z319) + (1 << 10)) >> 11;
    *(dataptr22 + 5) = (((tmp510 + z218) + z420) + (1 << 10)) >> 11;
    *(dataptr22 + 3) = (((tmp611 + z218) + z319) + (1 << 10)) >> 11;
    *(dataptr22 + 1) = (((tmp712 + z117) + z420) + (1 << 10)) >> 11;
    dataptr22 += 8;
    ctr23 --;
  }
  dataptr22 = data;
  ctr23 = 7;
  while (ctr23 >= 0) {
    cptr_jpeg_fdct_islow_326 ++;
    tmp05 = *(dataptr22 + 0) + *(dataptr22 + 56);
    tmp712 = *(dataptr22 + 0) - *(dataptr22 + 56);
    tmp16 = *(dataptr22 + 8) + *(dataptr22 + 48);
    tmp611 = *(dataptr22 + 8) - *(dataptr22 + 48);
    tmp27 = *(dataptr22 + 16) + *(dataptr22 + 40);
    tmp510 = *(dataptr22 + 16) - *(dataptr22 + 40);
    tmp38 = *(dataptr22 + 24) + *(dataptr22 + 32);
    tmp49 = *(dataptr22 + 24) - *(dataptr22 + 32);
    tmp1013 = tmp05 + tmp38;
    tmp1316 = tmp05 - tmp38;
    tmp1114 = tmp16 + tmp27;
    tmp1215 = tmp16 - tmp27;
    *(dataptr22 + 0) = ((tmp1013 + tmp1114) + (1 << 1)) >> 2;
    *(dataptr22 + 32) = ((tmp1013 - tmp1114) + (1 << 1)) >> 2;
    z117 = (tmp1215 + tmp1316) * 4433;
    *(dataptr22 + 16) = ((z117 + tmp1316 * 6270) + (1 << 14)) >> 15;
    *(dataptr22 + 48) = ((z117 + tmp1215 * -15137) + (1 << 14)) >> 15;
    z117 = tmp49 + tmp712;
    z218 = tmp510 + tmp611;
    z319 = tmp49 + tmp611;
    z420 = tmp510 + tmp712;
    z521 = (z319 + z420) * 9633;
    tmp49 *= 2446;
    tmp510 *= 16819;
    tmp611 *= 25172;
    tmp712 *= 12299;
    z117 *= -7373;
    z218 *= -20995;
    z319 *= -16069;
    z420 *= -3196;
    z319 += z521;
    z420 += z521;
    *(dataptr22 + 56) = (((tmp49 + z117) + z319) + (1 << 14)) >> 15;
    *(dataptr22 + 40) = (((tmp510 + z218) + z420) + (1 << 14)) >> 15;
    *(dataptr22 + 24) = (((tmp611 + z218) + z319) + (1 << 14)) >> 15;
    *(dataptr22 + 8) = (((tmp712 + z117) + z420) + (1 << 14)) >> 15;
    dataptr22 ++;
    ctr23 --;
  }
  goto Lret_jpeg_fdct_islow;
  }
  Lret_jpeg_fdct_islow: /* CIL Label */ ;
  }
  return;
}
}
