/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

int minver(int row , int col , double eps ) ;
int mmul(int row_a , int col_a , int row_b , int col_b ) ;
static double a[3][3]  = { {        3.0,        - 6.0,        7.0}, 
   {        9.0,        0.0,        - 5.0}, 
   {        5.0,        - 8.0,        6.0}};
double b[3][3]  ;
double c[3][3]  ;
double aa[3][3]  ;
double a_i[3][3]  ;
double e[3][3]  ;
double det  ;
double minver_fabs(double n ) 
{ 
  double f ;

  {
  if (n >= (double )0) {
    f = n;
  } else {
    f = - n;
  }
  return (f);
}
}
int main(void) 
{ 
  int i ;
  int j ;
  double eps ;
  int row4 ;
  int col5 ;
  double eps6 ;
  int work7[500] ;
  int i8 ;
  int j9 ;
  int k10 ;
  int r11 ;
  int iw12 ;
  int s13 ;
  int t14 ;
  int u15 ;
  int v16 ;
  double w17 ;
  double wmax18 ;
  double pivot19 ;
  double api20 ;
  double w121 ;
  double n1922 ;
  double f2023 ;
  double ret_minver_fabs2124 ;
  double n2225 ;
  double f2326 ;
  double ret_minver_fabs2427 ;
  int row_a28 ;
  int col_a29 ;
  int row_b30 ;
  int col_b31 ;
  int i32 ;
  int j33 ;
  int k34 ;
  int row_c35 ;
  int col_c36 ;
  double w37 ;

  {
  eps = 1.0e-6;
  i = 0;
  while (i < 3) {
    j = 0;
    while (j < 3) {
      aa[i][j] = a[i][j];
      j ++;
    }
    i ++;
  }
  {
  row4 = 3;
  col5 = 3;
  eps6 = eps;
  {
  if (row4 < 2) {
    goto Lret_minver;
  } else
  if (row4 > 500) {
    goto Lret_minver;
  } else
  if (eps6 <= 0.0) {
    goto Lret_minver;
  }
  w121 = 1.0;
  i8 = 0;
  while (i8 < row4) {
    work7[i8] = i8;
    i8 ++;
  }
  k10 = 0;
  while (k10 < row4) {
    wmax18 = 0.0;
    i8 = k10;
    while (i8 < row4) {
      {
      n1922 = a[i8][k10];
      {
      if (n1922 >= (double )0) {
        f2023 = n1922;
      } else {
        f2023 = - n1922;
      }
      {
      ret_minver_fabs2124 = f2023;
      goto Lret_minver_fabs;
      }
      }
      Lret_minver_fabs: /* CIL Label */ 
      w17 = ret_minver_fabs2124;
      }
      if (w17 > wmax18) {
        wmax18 = w17;
        r11 = i8;
      }
      i8 ++;
    }
    {
    pivot19 = a[r11][k10];
    n2225 = pivot19;
    {
    if (n2225 >= (double )0) {
      f2326 = n2225;
    } else {
      f2326 = - n2225;
    }
    {
    ret_minver_fabs2427 = f2326;
    goto Lret_minver_fabs___0;
    }
    }
    Lret_minver_fabs___0: /* CIL Label */ 
    api20 = ret_minver_fabs2427;
    }
    if (api20 <= eps6) {
      det = w121;
      goto Lret_minver;
    }
    w121 *= pivot19;
    u15 = k10 * col5;
    v16 = r11 * col5;
    if (r11 != k10) {
      w121 = - w17;
      iw12 = work7[k10];
      work7[k10] = work7[r11];
      work7[r11] = iw12;
      j9 = 0;
      while (j9 < row4) {
        s13 = u15 + j9;
        t14 = v16 + j9;
        w17 = a[k10][j9];
        a[k10][j9] = a[r11][j9];
        a[r11][j9] = w17;
        j9 ++;
      }
    }
    i8 = 0;
    while (i8 < row4) {
      a[k10][i8] /= pivot19;
      i8 ++;
    }
    i8 = 0;
    while (i8 < row4) {
      if (i8 != k10) {
        v16 = i8 * col5;
        s13 = v16 + k10;
        w17 = a[i8][k10];
        if (w17 != 0.0) {
          j9 = 0;
          while (j9 < row4) {
            if (j9 != k10) {
              a[i8][j9] -= w17 * a[k10][j9];
            }
            j9 ++;
          }
          a[i8][k10] = - w17 / pivot19;
        }
      }
      i8 ++;
    }
    a[k10][k10] = 1.0 / pivot19;
    k10 ++;
  }
  i8 = 0;
  while (i8 < row4) {
    while (1) {
      k10 = work7[i8];
      if (k10 == i8) {
        break;
      }
      iw12 = work7[k10];
      work7[k10] = work7[i8];
      work7[i8] = iw12;
      j9 = 0;
      while (j9 < row4) {
        u15 = j9 * col5;
        s13 = u15 + i8;
        t14 = u15 + k10;
        w17 = a[k10][i8];
        a[k10][i8] = a[k10][k10];
        a[k10][k10] = w17;
        j9 ++;
      }
    }
    i8 ++;
  }
  det = w121;
  goto Lret_minver;
  }
  Lret_minver: /* CIL Label */ ;
  i = 0;
  }
  while (i < 3) {
    j = 0;
    while (j < 3) {
      a_i[i][j] = a[i][j];
      j ++;
    }
    i ++;
  }
  {
  row_a28 = 3;
  col_a29 = 3;
  row_b30 = 3;
  col_b31 = 3;
  {
  row_c35 = row_a28;
  col_c36 = col_b31;
  if (row_c35 < 1) {
    goto Lret_mmul;
  } else
  if (row_b30 < 1) {
    goto Lret_mmul;
  } else
  if (col_c36 < 1) {
    goto Lret_mmul;
  } else
  if (col_a29 != row_b30) {
    goto Lret_mmul;
  }
  i32 = 0;
  while (i32 < row_c35) {
    j33 = 0;
    while (j33 < col_c36) {
      w37 = 0.0;
      k34 = 0;
      while (k34 < row_b30) {
        w37 += a[i32][k34] * b[k34][j33];
        k34 ++;
      }
      c[i32][j33] = w37;
      j33 ++;
    }
    i32 ++;
  }
  goto Lret_mmul;
  }
  Lret_mmul: /* CIL Label */ ;
  }
  return (0);
}
}
int mmul(int row_a , int col_a , int row_b , int col_b ) 
{ 
  int i ;
  int j ;
  int k ;
  int row_c ;
  int col_c ;
  double w ;

  {
  row_c = row_a;
  col_c = col_b;
  if (row_c < 1) {
    return (999);
  } else
  if (row_b < 1) {
    return (999);
  } else
  if (col_c < 1) {
    return (999);
  } else
  if (col_a != row_b) {
    return (999);
  }
  i = 0;
  while (i < row_c) {
    j = 0;
    while (j < col_c) {
      w = 0.0;
      k = 0;
      while (k < row_b) {
        w += a[i][k] * b[k][j];
        k ++;
      }
      c[i][j] = w;
      j ++;
    }
    i ++;
  }
  return (0);
}
}
int minver(int row , int col , double eps ) 
{ 
  int work[500] ;
  int i ;
  int j ;
  int k ;
  int r ;
  int iw ;
  int s ;
  int t ;
  int u ;
  int v ;
  double w ;
  double wmax ;
  double pivot ;
  double api ;
  double w1 ;
  double n19 ;
  double f20 ;
  double ret_minver_fabs21 ;
  double n22 ;
  double f23 ;
  double ret_minver_fabs24 ;

  {
  if (row < 2) {
    return (999);
  } else
  if (row > 500) {
    return (999);
  } else
  if (eps <= 0.0) {
    return (999);
  }
  w1 = 1.0;
  i = 0;
  while (i < row) {
    work[i] = i;
    i ++;
  }
  k = 0;
  while (k < row) {
    wmax = 0.0;
    i = k;
    while (i < row) {
      {
      n19 = a[i][k];
      {
      if (n19 >= (double )0) {
        f20 = n19;
      } else {
        f20 = - n19;
      }
      {
      ret_minver_fabs21 = f20;
      goto Lret_minver_fabs;
      }
      }
      Lret_minver_fabs: /* CIL Label */ 
      w = ret_minver_fabs21;
      }
      if (w > wmax) {
        wmax = w;
        r = i;
      }
      i ++;
    }
    {
    pivot = a[r][k];
    n22 = pivot;
    {
    if (n22 >= (double )0) {
      f23 = n22;
    } else {
      f23 = - n22;
    }
    {
    ret_minver_fabs24 = f23;
    goto Lret_minver_fabs___0;
    }
    }
    Lret_minver_fabs___0: /* CIL Label */ 
    api = ret_minver_fabs24;
    }
    if (api <= eps) {
      det = w1;
      return (1);
    }
    w1 *= pivot;
    u = k * col;
    v = r * col;
    if (r != k) {
      w1 = - w;
      iw = work[k];
      work[k] = work[r];
      work[r] = iw;
      j = 0;
      while (j < row) {
        s = u + j;
        t = v + j;
        w = a[k][j];
        a[k][j] = a[r][j];
        a[r][j] = w;
        j ++;
      }
    }
    i = 0;
    while (i < row) {
      a[k][i] /= pivot;
      i ++;
    }
    i = 0;
    while (i < row) {
      if (i != k) {
        v = i * col;
        s = v + k;
        w = a[i][k];
        if (w != 0.0) {
          j = 0;
          while (j < row) {
            if (j != k) {
              a[i][j] -= w * a[k][j];
            }
            j ++;
          }
          a[i][k] = - w / pivot;
        }
      }
      i ++;
    }
    a[k][k] = 1.0 / pivot;
    k ++;
  }
  i = 0;
  while (i < row) {
    while (1) {
      k = work[i];
      if (k == i) {
        break;
      }
      iw = work[k];
      work[k] = work[i];
      work[i] = iw;
      j = 0;
      while (j < row) {
        u = j * col;
        s = u + i;
        t = u + k;
        w = a[k][i];
        a[k][i] = a[k][k];
        a[k][k] = w;
        j ++;
      }
    }
    i ++;
  }
  det = w1;
  return (0);
}
}
