/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

extern int undet() ;
extern double dundet() ;
double my_sin(double rad , int *cptr_my_sin_1 , int *cptr_my_sin_2 , int *cptr_my_sin_3 ,
              int *cptr_my_sin_4 ) 
{ 
  double app ;
  double diff ;
  int inc ;
  int tmp ;

  {
  *cptr_my_sin_1 = 0;
  *cptr_my_sin_2 = 0;
  *cptr_my_sin_3 = 0;
  *cptr_my_sin_4 = 0;
  (*cptr_my_sin_1) ++;
  inc = 1;
  while (rad > (double )2 * 3.14159) {
    (*cptr_my_sin_2) ++;
    rad -= (double )2 * 3.14159;
  }
  while (rad < (double )-2 * 3.14159) {
    (*cptr_my_sin_3) ++;
    rad += (double )2 * 3.14159;
  }
  diff = rad;
  app = diff;
  diff = (diff * - (rad * rad)) / ((2.0 * (double )inc) * (2.0 * (double )inc + 1.0));
  app += diff;
  inc ++;
  while (1) {
    tmp = undet();
    if (! ((double )tmp >= 0.00001)) {
      break;
    }
    (*cptr_my_sin_4) ++;
    diff = (diff * - (rad * rad)) / ((2.0 * (double )inc) * (2.0 * (double )inc + 1.0));
    app += diff;
    inc ++;
  }
  return (app);
}
}
int main(void) 
{ 
  double rad ;
  double r ;
  int cptr_my_sin_1 ;
  int cptr_my_sin_2 ;
  int cptr_my_sin_3 ;
  int cptr_my_sin_4 ;
  int cptr_my_sin_5 ;
  int cptr_my_sin_6 ;
  int cptr_my_sin_7 ;
  int cptr_my_sin_8 ;
  double rad11 ;
  int *cptr_my_sin_112 ;
  int *cptr_my_sin_213 ;
  int *cptr_my_sin_314 ;
  int *cptr_my_sin_415 ;
  double app16 ;
  double diff17 ;
  int inc18 ;
  int tmp19 ;
  double ret_my_sin20 ;

  {
  {
  rad = dundet();
  rad11 = rad;
  cptr_my_sin_112 = & cptr_my_sin_1;
  cptr_my_sin_213 = & cptr_my_sin_2;
  cptr_my_sin_314 = & cptr_my_sin_3;
  cptr_my_sin_415 = & cptr_my_sin_4;
  {
  *cptr_my_sin_112 = 0;
  *cptr_my_sin_213 = 0;
  *cptr_my_sin_314 = 0;
  *cptr_my_sin_415 = 0;
  (*cptr_my_sin_112) ++;
  inc18 = 1;
  while (rad11 > (double )2 * 3.14159) {
    (*cptr_my_sin_213) ++;
    rad11 -= (double )2 * 3.14159;
  }
  while (rad11 < (double )-2 * 3.14159) {
    (*cptr_my_sin_314) ++;
    rad11 += (double )2 * 3.14159;
  }
  diff17 = rad11;
  app16 = diff17;
  diff17 = (diff17 * - (rad11 * rad11)) / ((2.0 * (double )inc18) * (2.0 * (double )inc18 + 1.0));
  app16 += diff17;
  inc18 ++;
  while (1) {
    tmp19 = undet();
    if (! ((double )tmp19 >= 0.00001)) {
      break;
    }
    (*cptr_my_sin_415) ++;
    diff17 = (diff17 * - (rad11 * rad11)) / ((2.0 * (double )inc18) * (2.0 * (double )inc18 + 1.0));
    app16 += diff17;
    inc18 ++;
  }
  {
  ret_my_sin20 = app16;
  goto Lret_my_sin;
  }
  }
  Lret_my_sin: /* CIL Label */ 
  r = ret_my_sin20;
  }
  return (0);
}
}
