/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

long a[50][50]  ;
long b[50]  ;
long x[50]  ;
int ludcmp(int nmax , int n ) ;
void main(void) 
{ 
  int i ;
  int j ;
  int nmax ;
  int n ;
  int chkerr ;
  long w ;
  int nmax7 ;
  int n8 ;
  int i9 ;
  int j10 ;
  int k11 ;
  long w12 ;
  long y13[100] ;
  int ret_ludcmp14 ;

  {
  nmax = 50;
  n = 5;
  i = 0;
  while (i <= n) {
    w = (long )0.0;
    j = 0;
    while (j <= n) {
      a[i][j] = (long )((i + 1) + (j + 1));
      if (i == j) {
        a[i][j] = (long )((double )a[i][j] * 2.0);
      }
      w += a[i][j];
      j ++;
    }
    b[i] = w;
    i ++;
  }
  {
  nmax7 = nmax;
  n8 = n;
  {
  i9 = 0;
  while (i9 < n8) {
    j10 = i9 + 1;
    while (j10 <= n8) {
      w12 = a[j10][i9];
      if (i9 != 0) {
        k11 = 0;
        while (k11 < i9) {
          w12 -= a[j10][k11] * a[k11][i9];
          k11 ++;
        }
      }
      a[j10][i9] = w12 / a[i9][i9];
      j10 ++;
    }
    j10 = i9 + 1;
    while (j10 <= n8) {
      w12 = a[i9 + 1][j10];
      k11 = 0;
      while (k11 <= i9) {
        w12 -= a[i9 + 1][k11] * a[k11][j10];
        k11 ++;
      }
      a[i9 + 1][j10] = w12;
      j10 ++;
    }
    i9 ++;
  }
  y13[0] = b[0];
  i9 = 1;
  while (i9 <= n8) {
    w12 = b[i9];
    j10 = 0;
    while (j10 < i9) {
      w12 -= a[i9][j10] * y13[j10];
      j10 ++;
    }
    y13[i9] = w12;
    i9 ++;
  }
  x[n8] = y13[n8] / a[n8][n8];
  i9 = n8 - 1;
  while (i9 >= 0) {
    w12 = y13[i9];
    j10 = i9 + 1;
    while (j10 <= n8) {
      w12 -= a[i9][j10] * x[j10];
      j10 ++;
    }
    x[i9] = w12 / a[i9][i9];
    i9 --;
  }
  {
  ret_ludcmp14 = 0;
  goto Lret_ludcmp;
  }
  }
  Lret_ludcmp: /* CIL Label */ 
  chkerr = ret_ludcmp14;
  }
  return;
}
}
int ludcmp(int nmax , int n ) 
{ 
  int i ;
  int j ;
  int k ;
  long w ;
  long y[100] ;

  {
  i = 0;
  while (i < n) {
    j = i + 1;
    while (j <= n) {
      w = a[j][i];
      if (i != 0) {
        k = 0;
        while (k < i) {
          w -= a[j][k] * a[k][i];
          k ++;
        }
      }
      a[j][i] = w / a[i][i];
      j ++;
    }
    j = i + 1;
    while (j <= n) {
      w = a[i + 1][j];
      k = 0;
      while (k <= i) {
        w -= a[i + 1][k] * a[k][j];
        k ++;
      }
      a[i + 1][j] = w;
      j ++;
    }
    i ++;
  }
  y[0] = b[0];
  i = 1;
  while (i <= n) {
    w = b[i];
    j = 0;
    while (j < i) {
      w -= a[i][j] * y[j];
      j ++;
    }
    y[i] = w;
    i ++;
  }
  x[n] = y[n] / a[n][n];
  i = n - 1;
  while (i >= 0) {
    w = y[i];
    j = i + 1;
    while (j <= n) {
      w -= a[i][j] * x[j];
      j ++;
    }
    x[i] = w / a[i][i];
    i --;
  }
  return (0);
}
}
